version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: my_mongo
    ports:
      - "27017:27017"

  page_admin_analytics:
    build:
      context: .
      dockerfile: ./services/pages/admin/analytics/Dockerfile
    depends_on:
      - mongo
    ports:
      - "8082:8082"
    env_file:
      - .docker.env

  page_admin_management:
    build:
      context: .
      dockerfile: ./services/pages/admin/management/Dockerfile
    depends_on:
      - mongo
    ports:
      - "8083:8083"
    env_file:
      - .docker.env

  db_realtime_updater:
    build:
      context: .
      dockerfile: ./services/db/updater/realtime/Dockerfile
    depends_on:
      - mongo
    ports:
      - "8084:8084"
    env_file:
      - .docker.env
